This is makeindex, version 2.17 [TeX Live 2025] (kpathsea + Thai support).
Scanning style file ./example.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file example.acn....done (35 entries accepted, 0 rejected).
Sorting entries....done (192 comparisons).
Generating output file example.acr....done (48 lines written, 0 warnings).
Output written in example.acr.
Transcript written in example.alg.
